# .github/workflows/app.yaml
name: CheckWebServiceImageProcessing 
on: push
jobs:
  python_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install requirements
        run: |
          #python -m pip install torch
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Pytest
        run: pytest
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install requirements
        env:
          RECAPTCHA_PRIVATE_KEY: '${{ secrets.RECAPTCHA_PRIVATE_KEY }}'
          RECAPTCHA_PUBLIC_KEY: '${{ secrets.RECAPTCHA_PUBLIC_KEY }}'
          SECRET_KEY: '${{secrets.SECRET_KEY}}'
        run: |
          sudo apt install gunicorn
          python -m pip install flask gunicorn requests flask-bootstrap flask-wtf pillow scipy matplotlib
      - name: Run
        run: |
          cd app
          ./st.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./app"
